- name: Update apt-cache
  apt:
    update_cache: yes
    cache_valid_time: 3600

- name: Install a list of packages
  apt:
    name: "{{ packages }}"
  vars:
    packages:
    - netbase
    - ca-certificates
    - libgmp10

