- name: Install pip and apt-based dependencies
  apt:
    name: "{{ packages }}"
  vars:
    packages:
      - python3-pip
      - python3-dev
      - python3-rtimulib
      - libatlas-base-dev
      - libopenjp2-7
      - libtiff5
    update_cache: yes

- name: Install sense-hat
  pip:
    name: 
      - sense-hat

