- name: Install the aptitude package
  apt:
    name: aptitude
    update_cache: yes
    force_apt_get: yes

- name: Update apt-cache
  apt:
    update_cache: yes
    cache_valid_time: 3600

- name: Install a list of packages
  apt:
    name: "{{ packages }}"
  vars:
    packages:
    - curl
    - git
    - gnupg2
    - mailutils
    - screen
    - sqlite3
    - vim
    - pass

